/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rental.view;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import rental.database.ConnectionDB;
import rental.database.Query;
import rental.util.Controller;

public class FormKendaraan extends javax.swing.JPanel {

    ConnectionDB cdb = new ConnectionDB();
    Query Query = new Query();
    Controller ctr = new Controller();
    PreparedStatement preStmt = null;
    Statement stms = null;
    ResultSet rst = null;

    /**
     * Creates new form FormLogin
     */
    public FormKendaraan() {
        initComponents();
        rdGroupJenis.add(rdMobil);
        rdGroupJenis.add(rdMotor);
        rdMobil.setSelected(true);
        rdGroupKondisi.add(rdBaik);
        rdGroupKondisi.add(rdRusak);
        rdBaik.setSelected(true);
        rdGroupStatus.add(rdTersedia);
        rdGroupStatus.add(rdSewa);
        rdTersedia.setSelected(true);
        txtSearch.setText("Search");
        viewTable();
        setIDKendaraan();
    }

    protected void viewTable() {
        rst = cdb.executeQuery(Query.SELECT_KENDARAAN_QUERY);
        tableKendaraan.setModel(DbUtils.resultSetToTableModel(rst));
        ((DefaultTableModel) tableKendaraan.getModel()).setColumnIdentifiers(new Object[]{"ID Kendaraan", "No Polisi", "Merek", "Warna", "Harga", "Tahun", "Jenis", "Kondisi", "Status"});
    }


    private void setIDKendaraan() {
        txtID.setText(ctr.autoKode(Query.SELECT_COUNT_KENDARAAN_QUERY, "K"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdGroupJenis = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        rdGroupKondisi = new javax.swing.ButtonGroup();
        rdGroupStatus = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        panelButton = new javax.swing.JLayeredPane();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKendaraan = new javax.swing.JTable();
        lblJenis = new javax.swing.JLabel();
        lblKondisi = new javax.swing.JLabel();
        rdMobil = new javax.swing.JRadioButton();
        rdBaik = new javax.swing.JRadioButton();
        rdRusak = new javax.swing.JRadioButton();
        lblStatus = new javax.swing.JLabel();
        rdTersedia = new javax.swing.JRadioButton();
        rdMotor = new javax.swing.JRadioButton();
        rdSewa = new javax.swing.JRadioButton();
        lblWarna = new javax.swing.JLabel();
        txtMerek = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        lblMerek = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblNopol = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNopol = new javax.swing.JTextField();
        lblTahun = new javax.swing.JLabel();
        cbTahun = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        lblHarga = new javax.swing.JLabel();
        txtWarna = new javax.swing.JTextField();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        setBackground(new java.awt.Color(255, 255, 255));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(475, 585));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblHeader.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblHeader.setText("Data Kendaraan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(lblHeader)
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        panelButton.setBorder(javax.swing.BorderFactory.createTitledBorder("Button"));
        panelButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panelButton.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 67, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        panelButton.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        panelButton.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 67, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        panelButton.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 67, -1));

        add(panelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 214, 113));

        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 241, -1));

        tableKendaraan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableKendaraan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableKendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKendaraanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKendaraan);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 309, 600, 250));

        lblJenis.setText("Jenis");
        add(lblJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        lblKondisi.setText("Kondisi");
        add(lblKondisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        rdMobil.setBackground(new java.awt.Color(255, 255, 255));
        rdMobil.setText("Mobil");
        add(rdMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        rdBaik.setBackground(new java.awt.Color(255, 255, 255));
        rdBaik.setText("Baik");
        add(rdBaik, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        rdRusak.setBackground(new java.awt.Color(255, 255, 255));
        rdRusak.setText("Rusak");
        add(rdRusak, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        lblStatus.setText("Status");
        add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        rdTersedia.setBackground(new java.awt.Color(255, 255, 255));
        rdTersedia.setText("Tersedia");
        add(rdTersedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        rdMotor.setBackground(new java.awt.Color(255, 255, 255));
        rdMotor.setText("Motor");
        add(rdMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        rdSewa.setBackground(new java.awt.Color(255, 255, 255));
        rdSewa.setText("Sewa");
        add(rdSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 57, -1));

        lblWarna.setText("Warna");
        add(lblWarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        add(txtMerek, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 176, -1));
        add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 176, -1));

        lblMerek.setText("Merek");
        add(lblMerek, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        lblID.setText("ID Kendaraan");
        add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        lblNopol.setText("Nomor Plat");
        add(lblNopol, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtID.setEnabled(false);
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 176, -1));
        add(txtNopol, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 176, -1));

        lblTahun.setText("Tahun");
        add(lblTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        cbTahun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));
        add(cbTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 124, -1));

        jPanel7.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 650, 30));

        lblHarga.setText("Harga Sewa");
        add(lblHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        add(txtWarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 176, -1));

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        if (txtSearch.getText().equals("")) {
            txtSearch.setText("Search");
        }
    }//GEN-LAST:event_txtSearchFocusLost

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        txtSearch.setText(null);
    }//GEN-LAST:event_txtSearchFocusGained

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        try {
            preStmt = cdb.updateStmt(Query.SELECT_LIKE_KENDARAAN_QUERY);
            preStmt.setString(1, "%" + txtSearch.getText() + "%");
            preStmt.setString(2, "%" + txtSearch.getText() + "%");
            preStmt.setString(3, "%" + txtSearch.getText() + "%");
            preStmt.setString(4, "%" + txtSearch.getText() + "%");
            preStmt.setString(5, "%" + txtSearch.getText() + "%");
            preStmt.setString(6, "%" + txtSearch.getText() + "%");
            preStmt.setString(7, "%" + txtSearch.getText() + "%");
            preStmt.setString(8, "%" + txtSearch.getText() + "%");
            rst = preStmt.executeQuery();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } finally {
            try {
                tableKendaraan.setModel(DbUtils.resultSetToTableModel(rst));
                ((DefaultTableModel) tableKendaraan.getModel()).setColumnIdentifiers(new Object[]{"ID Kendaraan", "No Polisi", "Merek", "Warna", "Harga", "Tahun", "Jenis", "Kondisi", "Status"});
                preStmt.close();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_txtSearchActionPerformed

    private void tableKendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKendaraanMouseClicked
        DefaultTableModel model = (DefaultTableModel) tableKendaraan.getModel();
        txtID.setText(model.getValueAt(tableKendaraan.getSelectedRow(), 0).toString());
        txtNopol.setText(model.getValueAt(tableKendaraan.getSelectedRow(), 1).toString());
        txtMerek.setText(model.getValueAt(tableKendaraan.getSelectedRow(), 2).toString());
        txtWarna.setText(model.getValueAt(tableKendaraan.getSelectedRow(), 3).toString());
        txtHarga.setText(model.getValueAt(tableKendaraan.getSelectedRow(), 4).toString());
        int index = Integer.parseInt(model.getValueAt(tableKendaraan.getSelectedRow(), 5).toString());
        cbTahun.setSelectedIndex(index - 2006);
        String rdJenis = model.getValueAt(tableKendaraan.getSelectedRow(), 6).toString();
        String rdKondisi = model.getValueAt(tableKendaraan.getSelectedRow(), 7).toString();
        String rdStatus = model.getValueAt(tableKendaraan.getSelectedRow(), 8).toString();
        if (rdJenis.equalsIgnoreCase("Mobil")) {
            rdMobil.setSelected(true);
        } else {
            rdMotor.setSelected(true);
        }
        if (rdKondisi.equalsIgnoreCase("Baik")) {
            rdBaik.setSelected(true);
        } else {
            rdRusak.setSelected(true);
        }
        if (rdStatus.equalsIgnoreCase("Tersedia")) {
            rdTersedia.setSelected(true);
        } else {
            rdSewa.setSelected(true);
        }
    }//GEN-LAST:event_tableKendaraanMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            if (!txtHarga.getText().isEmpty() && !txtMerek.getText().isEmpty() && !txtNopol.getText().isEmpty() && !txtWarna.getText().isEmpty()) {
                preStmt = cdb.updateStmt(Query.INSERT_KENDARAAN_QUERY);
                preStmt.setString(1, txtID.getText());
                preStmt.setString(2, txtNopol.getText());
                preStmt.setString(3, txtMerek.getText());
                preStmt.setString(4, txtWarna.getText());
                preStmt.setString(5, txtHarga.getText());
                preStmt.setString(6, cbTahun.getSelectedItem().toString());
                preStmt.setString(7, ctr.getSelectedButtonText(rdGroupJenis));
                preStmt.setString(8, ctr.getSelectedButtonText(rdGroupKondisi));
                preStmt.setString(9, ctr.getSelectedButtonText(rdGroupStatus));
                preStmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Berhasil ditambahkan !");
            } else {
                JOptionPane.showMessageDialog(this, "Lengkapi data terlebih dahulu !");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan !");
        } finally {
            try {
                viewTable();
                btnClearActionPerformed(evt);
                preStmt.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            if (tableKendaraan.getSelectedRow() == -1) {
                if (tableKendaraan.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(null, "Tabel Kosong !!");
                } else {
                    JOptionPane.showMessageDialog(null, "Pilih data Member !!");
                }
            } else {
                preStmt = cdb.updateStmt(Query.UPDATE_KENDARAAN_QUERY);
                preStmt.setString(1, txtNopol.getText());
                preStmt.setString(2, txtMerek.getText());
                preStmt.setString(3, txtWarna.getText());
                preStmt.setString(4, txtHarga.getText());
                preStmt.setString(5, cbTahun.getSelectedItem().toString());
                preStmt.setString(6, ctr.getSelectedButtonText(rdGroupJenis));
                preStmt.setString(7, ctr.getSelectedButtonText(rdGroupKondisi));
                preStmt.setString(8, ctr.getSelectedButtonText(rdGroupStatus));
                preStmt.setString(9, txtID.getText());
                preStmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil di Update !");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Data Gagal di Update !");
        } finally {
            try {
                viewTable();
                preStmt.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        setIDKendaraan();
        txtMerek.setText("");
        txtNopol.setText("");
        txtHarga.setText("");
        txtWarna.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            if (tableKendaraan.getSelectedRow() == -1) {
                if (tableKendaraan.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(null, "Tabel Kosong !!");
                } else {
                    JOptionPane.showMessageDialog(null, "Pilih data Kendaraan !!");
                }
            } else {
                preStmt = cdb.updateStmt(Query.DELETE_KENDARAAN_QUERY);
                preStmt.setString(1, txtID.getText());
                preStmt.executeUpdate();
                viewTable();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus !");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data gagal dihapus !");
        } finally {
            try {
                viewTable();
                preStmt.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cbTahun;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblJenis;
    private javax.swing.JLabel lblKondisi;
    private javax.swing.JLabel lblMerek;
    private javax.swing.JLabel lblNopol;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTahun;
    private javax.swing.JLabel lblWarna;
    private javax.swing.JLayeredPane panelButton;
    private javax.swing.JRadioButton rdBaik;
    private javax.swing.ButtonGroup rdGroupJenis;
    private javax.swing.ButtonGroup rdGroupKondisi;
    private javax.swing.ButtonGroup rdGroupStatus;
    private javax.swing.JRadioButton rdMobil;
    private javax.swing.JRadioButton rdMotor;
    private javax.swing.JRadioButton rdRusak;
    private javax.swing.JRadioButton rdSewa;
    private javax.swing.JRadioButton rdTersedia;
    private javax.swing.JTable tableKendaraan;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMerek;
    private javax.swing.JTextField txtNopol;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtWarna;
    // End of variables declaration//GEN-END:variables
}
