/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rental.view;

import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
import rental.database.ConnectionDB;
import rental.database.Query;

/**
 *
 * @author Alfian Hidayat
 */
public class Main extends javax.swing.JFrame {

    CardLayout layout = new CardLayout();
    public static FormMember panelMember;
    public static FormKendaraan panelKendaraan;
    public static FormPenyewaan panelPenyewaan;
    public static MenuUtama panelMenu;
    public static FormPengembalian panelPengembalian;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        panelMember = new FormMember();
        panelKendaraan = new FormKendaraan();
        panelPenyewaan = new FormPenyewaan();
        panelPengembalian = new FormPengembalian();
        panelMenu = new MenuUtama();
        getContentPane().setLayout(layout);
        getContentPane().add(panelMember);
        getContentPane().add(panelKendaraan);
        getContentPane().add(panelPenyewaan);
        getContentPane().add(panelMenu);
        getContentPane().add(panelPengembalian);
        setPaneNull();
        panelMenu.setVisible(true);
        if(isAdmin()){
            menuAkun.enable();
        }

    }

    public static void setPaneNull() {
        panelMember.setVisible(false);
        panelKendaraan.setVisible(false);
        panelPenyewaan.setVisible(false);
        panelMenu.setVisible(false);
        panelPengembalian.setVisible(false);
    }

    public boolean isAdmin() {
        try {
            ConnectionDB cdb = new ConnectionDB();
            Query Query = new Query();
            ResultSet rst = cdb.executeQuery(Query.SELECT_USER_ISADMIN_QUERY);
            if (rst.next()) {
                if (rst.getString(1).equals(FormLogin.akun)) {
                    return true;
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        return false;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();
        menuForm = new javax.swing.JMenu();
        meuFormMember = new javax.swing.JMenuItem();
        menuFormKendaraan = new javax.swing.JMenuItem();
        menuFormPengembalian = new javax.swing.JMenuItem();
        menuFormPenyewaan = new javax.swing.JMenuItem();
        sparatorMenuForm = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuAkun = new javax.swing.JMenuItem();
        menuGantiPass = new javax.swing.JMenuItem();
        sparatorMenuHelp = new javax.swing.JPopupMenu.Separator();
        menuLogOut = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Elektronik Rental");
        setResizable(false);

        menuBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        menuHome.setText("Home");
        menuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHomeMouseClicked(evt);
            }
        });
        menuBar.add(menuHome);

        menuForm.setText("Form");

        meuFormMember.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        meuFormMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/asset/member_icon.png"))); // NOI18N
        meuFormMember.setText("Member");
        meuFormMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meuFormMemberActionPerformed(evt);
            }
        });
        menuForm.add(meuFormMember);

        menuFormKendaraan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        menuFormKendaraan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/asset/car_icon.png"))); // NOI18N
        menuFormKendaraan.setText("Kendaraan");
        menuFormKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFormKendaraanActionPerformed(evt);
            }
        });
        menuForm.add(menuFormKendaraan);

        menuFormPengembalian.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuFormPengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/asset/return_icon.png"))); // NOI18N
        menuFormPengembalian.setText("Pengembalian");
        menuFormPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFormPengembalianActionPerformed(evt);
            }
        });
        menuForm.add(menuFormPengembalian);

        menuFormPenyewaan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuFormPenyewaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/asset/sewa_icon.png"))); // NOI18N
        menuFormPenyewaan.setText("Penyewaan");
        menuFormPenyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFormPenyewaanActionPerformed(evt);
            }
        });
        menuForm.add(menuFormPenyewaan);
        menuForm.add(sparatorMenuForm);

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/asset/exit_icon.png"))); // NOI18N
        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuForm.add(menuExit);

        menuBar.add(menuForm);

        menuHelp.setText("Help");

        menuAkun.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuAkun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/asset/akun_icon.png"))); // NOI18N
        menuAkun.setText("Akun");
        menuAkun.setEnabled(isAdmin());
        menuAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAkunActionPerformed(evt);
            }
        });
        menuHelp.add(menuAkun);

        menuGantiPass.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuGantiPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/asset/pass_icon.png"))); // NOI18N
        menuGantiPass.setText("Ganti Password");
        menuGantiPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGantiPassActionPerformed(evt);
            }
        });
        menuHelp.add(menuGantiPass);
        menuHelp.add(sparatorMenuHelp);

        menuLogOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menuLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/asset/log_out_icon.png"))); // NOI18N
        menuLogOut.setText("Log Out");
        menuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogOutActionPerformed(evt);
            }
        });
        menuHelp.add(menuLogOut);

        menuAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        menuAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/asset/about_icon.png"))); // NOI18N
        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        menuHelp.add(menuAbout);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meuFormMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meuFormMemberActionPerformed
        setPaneNull();
        panelMember.viewTable();
        panelMember.setVisible(true);
    }//GEN-LAST:event_meuFormMemberActionPerformed

    private void menuFormKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFormKendaraanActionPerformed
        setPaneNull();
        panelKendaraan.viewTable();
        panelKendaraan.setVisible(true);
    }//GEN-LAST:event_menuFormKendaraanActionPerformed

    private void menuFormPenyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFormPenyewaanActionPerformed
        setPaneNull();
        panelPenyewaan.viewTable();
        panelPenyewaan.setComboKendaraan();
        panelPenyewaan.setComboMember();
        panelPenyewaan.setVisible(true);
    }//GEN-LAST:event_menuFormPenyewaanActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        int a = JOptionPane.showConfirmDialog(panelMember, "Anda yakin ingin menutup aplikasi ini ?", "Warning", JOptionPane.WARNING_MESSAGE);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogOutActionPerformed
        int a = JOptionPane.showConfirmDialog(panelMember, "Anda yakin ingin keluar ?", "Warning", JOptionPane.WARNING_MESSAGE);
        if (a == 0) {
            dispose();
            new FormLogin().setVisible(true);
        }
    }//GEN-LAST:event_menuLogOutActionPerformed

    private void menuGantiPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGantiPassActionPerformed
        new GantiPassword().setVisible(true);
    }//GEN-LAST:event_menuGantiPassActionPerformed

    private void menuAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAkunActionPerformed
        new EditAkun().setVisible(true);
    }//GEN-LAST:event_menuAkunActionPerformed

    private void menuFormPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFormPengembalianActionPerformed
        setPaneNull();
        panelPengembalian.setVisible(true);
    }//GEN-LAST:event_menuFormPengembalianActionPerformed

    private void menuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseClicked
        setPaneNull();
        panelMenu.setVisible(true);
    }//GEN-LAST:event_menuHomeMouseClicked

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        new About().setVisible(true);
    }//GEN-LAST:event_menuAboutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuAkun;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuForm;
    private javax.swing.JMenuItem menuFormKendaraan;
    private javax.swing.JMenuItem menuFormPengembalian;
    private javax.swing.JMenuItem menuFormPenyewaan;
    private javax.swing.JMenuItem menuGantiPass;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuHome;
    private javax.swing.JMenuItem menuLogOut;
    private javax.swing.JMenuItem meuFormMember;
    private javax.swing.JPopupMenu.Separator sparatorMenuForm;
    private javax.swing.JPopupMenu.Separator sparatorMenuHelp;
    // End of variables declaration//GEN-END:variables
}
